---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment-4
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-4
  template:
    metadata:
      labels:
        app: kafka-4
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:7.0.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "4"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper-service:2181'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service-4:9095
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-4
spec:
  selector:
    app: kafka-2
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9092
