---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment-2
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:7.0.1
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          value: "2"        
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper-service:2181'
        - name : KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT          
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL 


        - name: KAFKA_LISTENERS
          value: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka-service-2:29092,EXTERNAL://172.31.216.72:30084        
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
spec:
  type: NodePort
  selector:
    app: kafka-2
  ports:
    - name: external
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30084

    - name: internal
      protocol: TCP
      port: 29092
      targetPort: 29092