---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:7.0.1
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"     
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper-service:2181'       
        - name : KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT          
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL       

  
        - name: KAFKA_LISTENERS
          value: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka-service:29092,EXTERNAL://172.31.216.72:30083      

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: external
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30083

    - name: internal
      protocol: TCP
      port: 29092
      targetPort: 29092

#listeners=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
#listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#advertised.listeners=INTERNAL://ip-172-31-18-160.us-west-2.compute.internal:19092,EXTERNAL://ec2-54-191-84-122.us-west-2.compute.amazonaws.com:9092
#inter.broker.listener.name=INTERNAL